fun main() {
    val badGuy = NPC(100, 30)
    val hero = Hero(200, 20, "imka239")
    val minion = Minion(300, 10)
    hero.setMinion(minion)
    badGuy.getInfo()
    hero.getInfo()
    println()
    hero.fight(badGuy)
    badGuy.getInfo()
    hero.getInfo()
    println()
    hero.fight(badGuy)
    badGuy.getInfo()
    hero.getInfo()
    println()
    hero.fight(badGuy)
    badGuy.getInfo()
    hero.getInfo()
    println()
    hero.fight(badGuy)
    badGuy.getInfo()
    hero.getInfo()
    println()
    hero.fight(badGuy)
    badGuy.getInfo()
    hero.getInfo()
    println()
    hero.fight(badGuy)
    badGuy.getInfo()
    hero.getInfo()
    println()
    hero.fight(badGuy)
    badGuy.getInfo()
    hero.getInfo()
}